name: Trigger Netlify Rebuild
on:
  schedule:
    - cron: '5 13 * * THU'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
      - shell: bash
        env:
          NETLIFY_HOOK_TOKEN: ${{ secrets.NETLIFY_HOOK_TOKEN }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/$
